### PR TITLE
Added guard with key art

### PR DESCRIPTION
**Pull request by LewisJHill**
Added some visuals for the guards room. #3

### CODE REVIEW

**Comment by farhayden** [comment]
Nice ascii art, looks great.

**Comment by LewisJHill** [comment]
New shortcut method for easy access to the second floor. When you are in the dungeon you can type "VENT" to take you to the Great Hall #3

**Review by TeAwa-Whetu — APPROVED** [review]
Nice, I really do like the ASCII art for the king and queen, reminds me of a perfect film I know. Also interesting change with making the cases for the switch into strings, id imagine this helps eliminate potential player errors.

**Review by ALADM2 — APPROVED** [review]
Nice guard!!

**Pull request merged**
